### ISSUE TITLE
2 Twilights Sparkles

### ISSUE THREAD

**Issue by ArtoxWolf** [Xperidia/FNAPGM#1]
Me And My Frend Played FNAP but thun suddenly there was 2 twilights (one stage fixed and one in the kitchen without the face)

here is pootis proof

https://www.youtube.com/watch?v=h8i1XhgO3WI
couldnt post file coz it was too fat (stupid "smaller than 10MB" thing) so heres the link

**Comment by VickyFrenzy** [comment]
This is normal, don't worry there is really two Twilights:
- The Twilight on stage do nothing.
- The broken Twilight is the only one to attack you.
